version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=parser_db
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser_pass
    ports:
      - "6543:5432"
  queue:
    image: rabbitmq:latest
  backend:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: app.dockerfile
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    volumes:
      - ./:/backend/
    ports:
      - 80:80
  celeryworker:
    build:
      context: ./
      dockerfile: celeryworker.dockerfile
    command: sh -c "celery -A app.worker.celery_app worker --loglevel=INFO -c 1"
    depends_on:
      - db
      - queue
