"""init db

Revision ID: ec26d66a706f
Revises: 
Create Date: 2021-05-16 17:38:50.242517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec26d66a706f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_results',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False, comment='url для парсинга'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата парсинга url'),
    sa.Column('result', sa.String(length=255), nullable=False, comment='Результат парсинга'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_results_url'), 'parse_results', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_results_url'), table_name='parse_results')
    op.drop_table('parse_results')
    # ### end Alembic commands ###
